package pawelmadela.calendar.enums;


/**
 * Represents type which provides information about response from services and store message to controller
 */
public enum UserServiceResponseStatus {

    USERNAME_EXISTS,
    EMAIL_EXISTS,
    USERID_EXISTS,
    PASSWORD_INCORRECT,
    USERNAME_NOT_FOUND,
    USERID_NOT_FOUND,
    EMAIL_NOT_FOUND,
    USERNAME_FOUND,
    UNEXPECTED_ERROR,
    USER_CREATED,
    EMAIL_CHANGED_SUCCESSFULL,
    PASSWORD_CHANGED_SUCESSFULL,
    RESULT_FOUND,
    RESULT_NOT_FOUND,
    SAME_PASSWORD,
    USER_DELETED,
    NULL_CREDENTIALS,
    SERVER_CONNECTION_FAILURE,
    SAME_EMAIL,
    STATUS_NOT_FOUND,
    STATUS_CHANGED_SUCCESFULL,
    WRONG_ACCOUNT_STATUS,
    REGISTRATION_SUCCESSFULL,
    REG_TOKEN_NOT_VALID,
    INVALID_ACCOUNT_TYPE;
}
